### PR TITLE
Fix nightly 1.67.0 changes

### PR DESCRIPTION
**Pull request by Hpmason**
I created an issue on this #39 talking about the problem. There haven't been any replies on whether or not a PR would be looked at, but I figured I'd submit my own PR with nightly changes just in case.

I'd be more than happy to make any additional changes suggested/needed.

Main changes:
- Update asm macros since stablization
- Update new trait bounds for Fn-Family of traits

### CODE REVIEW

**Comment by Huskehhh** [comment]
Broken again on `1.68.0-nightly` (9c07efe84)

**Comment by Hpmason** [comment]
> Broken again on `1.68.0-nightly` (9c07efe84)

I just tested the newest nightly (1.68.0-nightly, d0dc9efff) on both Windows and WSL. crate builds and the tests all pass. What was the issue you're having?

**Comment by Huskehhh** [comment]
My apologies, you're correct it works fine :)

**Comment by MolotovCherry** [comment]
Until this gets accepted into master and released, this is the fix in Cargo.toml
`detour = { git = "https://github.com/Hpmason/detour-rs", branch = "fix-nightly1.67.0-changes" }`

Thanks for fixing this Hpmason

**Comment by Hpmason** [comment]
Doesn't seem like anyone is able to checkout/handle this PR, so I'm going to close it for now. I feel bad triggering CI with every commit, but I still want to keep fixing/improving minor things. 

If any of the maintainers wish to use my fork or my changes, I can reopen this PR at another time (or they can just take my changes).

**Comment by Hpmason** [comment]
> Until this gets accepted into master and released, this is the fix in Cargo.toml `detour = { git = "https://github.com/Hpmason/detour-rs", branch = "fix-nightly1.67.0-changes" }`

Just an fyi for any that finds this, I've renamed the repo/crate, so setting the dependency like this will fail!
Use one of these instead:
```toml
retour = "0.1.0"
# or
retour = { git = "https://github.com/Hpmason/retour-rs" }
```

**Pull request closed without merging**
